region: us-east-1

metrics:

  # =========================
  # EC2
  # =========================

  - aws_namespace: AWS/EC2
    aws_metric_name: CPUUtilization
    aws_dimensions:
      - InstanceId
    aws_statistics:
      - Average

  # =========================
  # ECS
  # =========================

  - aws_namespace: AWS/ECS
    aws_metric_name: CPUUtilization
    aws_dimensions:
      - ClusterName
    aws_statistics:
      - Average

  - aws_namespace: AWS/ECS
    aws_metric_name: MemoryUtilization
    aws_dimensions:
      - ClusterName
    aws_statistics:
      - Average

  - aws_namespace: AWS/ECS
    aws_metric_name: CPUUtilization
    aws_dimensions:
      - ClusterName
      - ServiceName
    aws_statistics:
      - Average

  - aws_namespace: AWS/ECS
    aws_metric_name: MemoryUtilization
    aws_dimensions:
      - ClusterName
      - ServiceName
    aws_statistics:
      - Average

  # =========================
  # ALB
  # =========================

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: RequestCount
    aws_dimensions:
      - LoadBalancer
    aws_statistics:
      - Sum

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: TargetResponseTime
    aws_dimensions:
      - LoadBalancer
    aws_statistics:
      - Average

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HealthyHostCount
    aws_dimensions:
      - LoadBalancer
    aws_statistics:
      - Average

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: UnHealthyHostCount
    aws_dimensions:
      - LoadBalancer
    aws_statistics:
      - Average

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_2XX_Count
    aws_dimensions:
      - LoadBalancer
    aws_statistics:
      - Sum

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_4XX_Count
    aws_dimensions:
      - LoadBalancer
    aws_statistics:
      - Sum

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_5XX_Count
    aws_dimensions:
      - LoadBalancer
    aws_statistics:
      - Sum

  # =========================
  # EKS CONTROL PLANE
  # =========================

  - aws_namespace: AWS/EKS
    aws_metric_name: apiserver_request_total
    aws_dimensions:
      - ClusterName
    aws_statistics:
      - Sum
